# Generated by Django 2.2 on 2020-04-20 00:15

import datetime
from django.db import migrations, models
import todo.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200415_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={},
        ),
        migrations.AddField(
            model_name='tasklist',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='todo_images', validators=[todo.api.validators.validate_file_size, todo.api.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 6, 15, 41, 770858)),
        ),
    ]
