# Generated by Django 2.2 on 2020-04-20 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200420_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 7, 20, 54, 182587)),
        ),
    ]
