# Generated by Django 2.2 on 2020-04-15 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': 'Task list', 'verbose_name_plural': 'Task lists'},
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 15, 16, 54, 40, 886280)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 15, 16, 54, 40, 886280)),
        ),
    ]
